### ISSUE TITLE
Only the hint/note on the introduction page of the documentation is well formatted

### ISSUE THREAD

**Issue by Ifycode** [Ifycode/git-github-training-resource#12]
#### Problem
`Reload any one page from this documentation (whenever you come back to continue this training) so that newly added content can show up (if any new content has been added).`

The above text/sentence appears towards the bottom of some pages of the documentation. But only the one on the [introduction page](https://obiagba-mary.gitbook.io/git-and-github-training) is properly formatted as a hint. On every other page, it appears as ordinary text. 

#### Task description and expected result
Make the sentence above show up properly formatted as a hint, on every page where the text/sentence exists.

> **Note**
> Find files to update in the doc folder of this repository

**Comment by Danbaba1** [comment]
@Ifycode I am interested in this issue.

**Comment by Ifycode** [comment]
Assigned to you @Danbaba1
