### ISSUE TITLE
Embed 4 new video resources for Part 1 Set 1 in the Gitbook learning resource

### ISSUE THREAD

**Issue by Ifycode** [Ifycode/git-github-training-resource#16]
Our [Part 1 set 1 page of the Gitbook learning resource](https://obiagba-mary.gitbook.io/git-and-github-training/part-1-github-ui/set-1-github-ui-learning-videos-and-tasks) currently does not contain any video.

#### Task description and expected result
Replace the "Work in progress page" text with youtube videos. Embed the new video resources below on Part 1 set 1 page:
- https://youtu.be/W8TIY7mbvXo
- https://youtu.be/DWAgcmMEiXE
- https://youtu.be/IqJWDTZdQG4
- https://youtu.be/Gt0ORe5aIx4

#### Additional information
- You are not just embedding only. Each video should be in a section. The section title for each video should be determined by the video title on youtube. For example, on youtube, the first video in the list above has the title - **Git and Github training # 3: Github UI - Forking a repo, and how to know which branch you are in**. The section title for this video should therefore be **Forking a repo, and how to know which branch you are in**. Use the same idea for other youtube videos.
- Just use "youtube video" as the caption for all 4 videos

**Comment by ManasviGoyal** [comment]
Hi. I would like to try this one too. I would like to clarify one thing. By caption, you mean the text below the video (like I the image) or the bold heading (which I assume should be the title)?

![image](https://user-images.githubusercontent.com/55101825/193481659-c6851d1f-c4b2-4e90-9012-faade8a83ef4.png)

**Comment by Ifycode** [comment]
Nice pick. Assigned to you @ManasviGoyal 
The tiny text below the video is the caption.
