### ISSUE TITLE
Help contributors know where they can find files to update when contributing to the learning resource

### ISSUE THREAD

**Issue by Ifycode** [Ifycode/git-github-training-resource#17]
#### Problem
The file(s) to update are in the doc folder of this repository. But our contributors don't know that yet. Help contributors know where they can find files to update when contributing to the learning resource. 

#### Task description
- Add a hint just after the last list item under the **Learning resource repo: How to submit your changes** section of the [making and submitting changes page](https://obiagba-mary.gitbook.io/git-and-github-training/contributors-guide/making-and-submitting-changes).
- The hint should tell contributors interested in improving the content of the learning resource to find files to update in the doc folder of the [Learning resource repo](https://github.com/Ifycode/git-github-training-resource).

**Comment by ManasviGoyal** [comment]
I would like to work on this

**Comment by Ifycode** [comment]
Hi @ManasviGoyal 
Please go ahead. Assigned to you!
