### ISSUE TITLE
Help interested contributors know that they can benefit from the training too!

### ISSUE THREAD

**Issue by Ifycode** [Ifycode/git-github-training-resource#18]
We want our contributors to benefit from taking the training too!

#### Task description
- Add a hint just before the **Learning resource repo: How to submit your changes** section of the [making and submitting changes page](https://obiagba-mary.gitbook.io/git-and-github-training/contributors-guide/making-and-submitting-changes).
- The hint should tell interested contributors that taking the [Git and Github training](https://obiagba-mary.gitbook.io/git-and-github-training) can help them better contribute to the Git and Github training project (and any other Github projects they will be taking on in the future).

**Comment by oyenuga17** [comment]
I am interested @Ifycode

**Comment by Ifycode** [comment]
Assigned to you @oyenuga17 👍
