### ISSUE TITLE
Update the purpose of this training on the introduction page of the Gitbook learning resource

### ISSUE THREAD

**Issue by Ifycode** [Ifycode/git-github-training-resource#23]
#### Problem
The purpose of the training written on the [introduction page of the gitbook learning resource](https://obiagba-mary.gitbook.io/git-and-github-training) says: "The purpose of the Git & Github training videos and exercises added here is to help with interacting with a repository that is not yours".
But this is just one of the many purposes the training came into existence.

#### Task description and Expected result
That part of the page should highlight all purposes in form of a description and a list as shown below.

The purpose of the Git & Github training videos and exercises added here is to provide an interactive platform, that will help prepare learners for internships and jobs that require the use of git and GitHub. There will be no code-related content, the only type of files the training will use are files with `.md` extensions. The content of the training will help to understand and practice:
- GitHub contributions
- Use of the Github UI
- Use of command line
- Git workflow
- Using Git and github for collaboration

**Comment by anirudh0806** [comment]
I would love to contribute. What is the procedure for doing so?

**Comment by Ifycode** [comment]
Hi @anirudh0806
Please check this page for instructions on how to contribute: https://obiagba-mary.gitbook.io/git-and-github-training/contributors-guide/making-and-submitting-changes. 

Would you like me to assign this task to you?

**Comment by Ifycode** [comment]
This has been fixed. closing this.

**Comment by Ifycode** [comment]
@all-contributors add @all-contributors for doc
