### ISSUE TITLE
Help interested contributors know that they can add the gitbook training resource to their portfolio

### ISSUE THREAD

**Issue by Ifycode** [Ifycode/git-github-training-resource#25]
We want our contributors to know that they can share that they are contributors to the [Git and GitHub gitbook training resource](https://obiagba-mary.gitbook.io/git-and-github-training) on their portfolio!

#### Task description
- Add a hint just before the **Learning resource repo: How to submit your changes** section of the [making and submitting changes page](https://obiagba-mary.gitbook.io/git-and-github-training/contributors-guide/making-and-submitting-changes).
- The hint should tell interested contributors that they can indicate share they are contributors to the [Git and GitHub gitbook training resource](https://obiagba-mary.gitbook.io/git-and-github-training) on their portfolio, as long as they are among contributors listed in the [contributors section](https://github.com/Ifycode/git-github-training-resource#contributors-). Anyone who has contributed and has not been added to the contributors list should [notify repo admins through the learning resource repo's discussion](https://github.com/Ifycode/git-github-training-resource/discussions/2).

**Comment by oyenuga17** [comment]
i am interested @Ifycode

**Comment by Ifycode** [comment]
Assigned to you @oyenuga17
