### ISSUE TITLE
Add contribution rules section to help contributions know the important things to do while making changes

### ISSUE THREAD

**Issue by Ifycode** [Ifycode/git-github-training-resource#27]
We want our contributors to know the following are important while making contributions to the training resources:
- Interested contributors are to show interest by commenting on the issue they want to work on, in other to get assigned to the issue. Submitting a pull request for an issue you are not assigned to will only be counted as spam. You will be unassigned from an issue if you do not submit a pull request for that issue after 2 days of showing interest.
- Contributions should be done as instructed in [Learning resource repo: How to submit your changes](https://obiagba-mary.gitbook.io/git-and-github-training/contributors-guide/making-and-submitting-changes#learning-resource-repo-how-to-submit-your-changes) or [Training repo: How to submit your changes](https://obiagba-mary.gitbook.io/git-and-github-training/contributors-guide/making-and-submitting-changes#training-repo-how-to-submit-your-changes), depending on the repository you are working on.
- Pull request title must reflect the Issue title you are working on, and it should start with "Fix: ". For example, If the issue title is "Add contribution rules section to help contributions know the important things to do while making changes", the pull request title should be "Fix: Add contribution rules section to help contributions know the important things to do while making changes".
- Pull request should be linked issue it aims to fix.
- Feel free to ask questions if you are not clear about something in the issue you are working on.

#### Task description
- Create a section called **Contribution guidelines to follow** just before the [Learning resource repo: How to submit your changes](https://obiagba-mary.gitbook.io/git-and-github-training/contributors-guide/making-and-submitting-changes#learning-resource-repo-how-to-submit-your-changes) section.
- Add the guidelines above in form of a list under this new section you have created.

**Comment by YashPimple** [comment]
@Ifycode can you assign it to me would like to work on it?

**Comment by Ifycode** [comment]
Assigned to you @YashPimple 👍🏽

**Comment by Ifycode** [comment]
Anyone interested in taking up this issue can comment here to show their interest.

**Comment by YashPimple** [comment]
@Ifycode i am working on it and will raise a PR soon.

**Comment by Ifycode** [comment]
Oh... All right. I did not know. Sorry about that @YashPimple 
You don't have to finish the issue before submitting a PR. This way, I would know you are still working on the issue, and I would be able to help better if you have any issues.
Do you have any issues?

**Comment by YashPimple** [comment]
> Oh... All right. I did not know. Sorry about that @YashPimple You don't have to finish the issue before submitting a PR. This way, I would know you are still working on the issue, and I would be able to help better if you have any issues. Do you have any issues?

Sorry for the inconvenience I forgot to raise the PR within 2 days.
