### ISSUE TITLE
Update the purpose of this training in the training repo and in the documentation repo

### ISSUE THREAD

**Issue by Ifycode** [Ifycode/git-github-training-resource#3]
#### Problem
The purpose of the training written in the readme file found **at the root of the** [training repo](https://github.com/Ifycode/git-github-training), and in the readme file found **in the doc folder of the** [documentation repo](https://github.com/Ifycode/git-github-training-documentation) says: "Git & Github training videos and exercises added here is to help with interacting with a repository that is not yours".
But this is just one of the many purposes the training came into existence.

#### Task description and Expected result
That part of both readme files should highlight all purposes in form of a description and a list as shown below.

The purpose of the Git & Github training videos and exercises added here is to provide an interactive platform, that will help prepare learners for internships and jobs that require the use of git and GitHub. There will be no code-related content, the only type of files the training will use are files with `.md` extensions. The content of the training will help to understand and practice:
- GitHub contributions
- Use of the Github UI
- Use of command line
- Git workflow

> Note 1: This means you are to work on and send pull requests to the 2 repos concerned.
> Note 2: Show interest that you want to work on this issue by typing a comment under this issue.

> Extra note: Once your changes have been merged into the one for the documentation repo, the changes you submitted will automatically show up on this page of the live documentation: https://obiagba-mary.gitbook.io/git-and-github-training.

**Comment by Danbaba1** [comment]
I am interested. @Ifycode

**Comment by Ifycode** [comment]
Assigned to you! @Danbaba1

**Comment by Ifycode** [comment]
@all-contributors add @Ifycode for tutorials
