### ISSUE TITLE
Embed task video in task section on the Part 1 set 1 page of the Gitbook training resource

### ISSUE THREAD

**Issue by Ifycode** [Ifycode/git-github-training-resource#33]
The Task video for Part 1 set 1 has been added to our youtube playlist but has not been embedded yet in the gitbook resource.
#### Task description and expected result
- On the [Part 1 set 1 page ](https://obiagba-mary.gitbook.io/git-and-github-training/part-1-github-ui/set-1-github-ui-learning-videos-and-tasks), under the **Task** section replace the text `Task video goes here. Videos not available yet. Check back on the 9th of October 2022.` with an embedded youtube video.
- This is the youtube video to embed: https://youtu.be/SNfWwGD7UuI
- The video caption should be "Tasks 1 and 2 for Part 1 set 1"

**Comment by JaisonBinns** [comment]
Can I take this issue?

**Comment by Ifycode** [comment]
Yes, assigned to you @JaisonBinns 
The guideline written here should guide you on how to make and submit your changes: https://obiagba-mary.gitbook.io/git-and-github-training/contributors-guide/making-and-submitting-changes.
Let me know if you have any questions or run into any issue.
