### ISSUE TITLE
Embed 2 new learning video resources for Part 1 Set 1 in the Gitbook learning resource

### ISSUE THREAD

**Issue by Ifycode** [Ifycode/git-github-training-resource#34]
Two new learning videos have been added to our youtube playlist, but have not been added to our [Part 1 set 1 page of the Gitbook learning resource](https://obiagba-mary.gitbook.io/git-and-github-training/part-1-github-ui/set-1-github-ui-learning-videos-and-tasks).

#### Task description and expected result
Go to the **Learning videos** section, embed these videos in certain positions:
- First youtube video: https://youtu.be/A2gqOvGpH_0. Embed this video before the **Managing files and folders (create, edit and delete)** section
- Second youtube video:  https://youtu.be/gGpH3kdbQns. Embed this video after the **When to delete a branch connected to pull request or a fork** section. 

#### Additional information
- You are not just embedding only. Each video should be in a section. The section title for each video should be determined by the video title on youtube. For example, on youtube, if a video has the title - **Git and Github training # 3: Github UI - Forking a repo, and how to know which branch you are in**. The section title for this video should therefore be **Forking a repo, and how to know which branch you are in**. Use the same idea for the youtube videos you are embedding.
- Just use "youtube video" as the caption for the 2 videos

**Comment by Kesav890** [comment]
can i have this issue?

**Comment by Ifycode** [comment]
Yes, assigned to you @Kesav890
The guideline written here should guide you on how to make and submit your changes: https://obiagba-mary.gitbook.io/git-and-github-training/contributors-guide/making-and-submitting-changes. 
Let me know if you have any questions or run into any issue.

**Comment by Ifycode** [comment]
Closing this because this has been fixed.
