### ISSUE TITLE
Embed 2 missing learning video resources in Part 1 Set 1 in the Gitbook learning resource

### ISSUE THREAD

**Issue by Ifycode** [Ifycode/git-github-training-resource#39]
Two new learning videos have been added to our youtube playlist, but have not been added to our [Part 1 set 1 page of the Gitbook learning resource](https://obiagba-mary.gitbook.io/git-and-github-training/part-1-github-ui/set-1-github-ui-learning-videos-and-tasks).

#### Task description and expected result
Under the **Learning videos** section, you will find this text:
`Some other set 1 learning videos are not available yet. Check back on the 9th of October 2022.`
Remove this text, and add these 2 videos at that position: 
- https://youtu.be/lqSdpFmT3y4
- https://youtu.be/K8PmM6mRLIo

#### Additional information
- You are not just embedding only. Each video should be in a section. The section title for each video should be determined by the video title on youtube. For example, on youtube, if a video has the title - **Git and Github training # 3: Github UI - Forking a repo, and how to know which branch you are in**. The section title for this video should therefore be **Forking a repo, and how to know which branch you are in**. Use the same idea for the youtube videos you are embedding.
- Just use "youtube video" as the caption for the 2 videos

**Comment by rk-1620** [comment]
@Ifycode I would like to solve this issue. Please assign it to me.

**Comment by Ifycode** [comment]
Hi @rk-1620.
Assigned to you 👍

The guideline written here should guide you on how to make and submit your changes: https://obiagba-mary.gitbook.io/git-and-github-training/contributors-guide/making-and-submitting-changes.
Let me know if you have any questions or run into any issue.
