### ISSUE TITLE
Convert Introduction text to link in training repo readme

### ISSUE THREAD

**Issue by Ifycode** [Ifycode/git-github-training-resource#4]
#### Task description
- Go to the readme file of the [training repo](https://github.com/Ifycode/git-github-training)
- Convert the list item text "Video: Introduction" to a link that leads to: https://obiagba-mary.gitbook.io/git-and-github-training/#watch-video-introduction

**Comment by Danbaba1** [comment]
@Ifycode  I am interested.

**Comment by Ifycode** [comment]
Assigned to you @Danbaba1

**Comment by Ifycode** [comment]
This is kind of urgent, so I'm fixing this. Since you are not available to fix this @Danbaba1
