### ISSUE TITLE
Embed training videos #12 and #13 in Part 1 Set 2 page of the Gitbook learning resource

### ISSUE THREAD

**Issue by Ifycode** [Ifycode/git-github-training-resource#45]
New learning videos have been added to our youtube playlist, but have not been added to our [Part 1 set 2 page of the Gitbook learning resource](https://obiagba-mary.gitbook.io/git-and-github-training/part-1-github-ui/set-2-learning-videos-and-tasks).

#### Task description and expected result
Go to the **Learning videos** section, and embed these videos before the text:
- https://youtu.be/Rx14ka5M3cc
- https://youtu.be/bnlvtzsL7sY

#### Additional information
- You are not just embedding only. Each video should be in a section. The section title for each video should be determined by the video title on youtube. For example, on youtube, if a video has the title - **Git and Github training # 3: Github UI - Forking a repo, and how to know which branch you are in**. The section title for this video should therefore be **Forking a repo, and how to know which branch you are in**. Use the same idea for the youtube videos you are embedding.
- Just use "youtube video" as the caption for the 2 videos

**Comment by Danbaba1** [comment]
@Ifycode I am interested in this issue.

**Comment by Ifycode** [comment]
@Danbaba1 assigned to you.
The guideline written here should guide you on how to make and submit your changes: https://obiagba-mary.gitbook.io/git-and-github-training/contributors-guide/making-and-submitting-changes.
Let me know if you have any questions or run into any issues.

**Comment by Ifycode** [comment]
@Danbaba1 This page is an example: https://obiagba-mary.gitbook.io/git-and-github-training/part-1-github-ui/set-1-learning-videos-and-tasks

You will see small text saying "YouTube Video" under most videos there. That's the caption.

**Comment by Danbaba1** [comment]
@Ifycode Okay ma I have seen them. I want to give it a shot.
