### ISSUE TITLE
Embed training videos #14 and #15 in Part 1 Set 2 page of the Gitbook learning resource

### ISSUE THREAD

**Issue by Ifycode** [Ifycode/git-github-training-resource#46]
New learning videos have been added to our youtube playlist, but have not been added to our [Part 1 set 2 page of the Gitbook learning resource](https://obiagba-mary.gitbook.io/git-and-github-training/part-1-github-ui/set-2-learning-videos-and-tasks).

#### Task description and expected result
Go to the **Learning videos** section, and replace the text there with the videos below (i.e. embed the videos):
- https://youtu.be/hRFBG3lMq9k
- https://youtu.be/Ej396Vra1oQ

#### Additional information
- You are not just embedding only. Each video should be in a section. The section title for each video should be determined by the video title on youtube. For example, on youtube, if a video has the title - **Git and Github training # 3: Github UI - Forking a repo, and how to know which branch you are in**. The section title for this video should therefore be **Forking a repo, and how to know which branch you are in**. Use the same idea for the youtube videos you are embedding.
- Just use "youtube video" as the caption for the 2 videos

**Comment by oyenuga17** [comment]
I am interested @Ifycode

**Comment by Ifycode** [comment]
Assigned to you @oyenuga17 👍🏽
