### ISSUE TITLE
Embed task video in tasks section on the Part 1 set 2 page of the Gitbook training resource

### ISSUE THREAD

**Issue by Ifycode** [Ifycode/git-github-training-resource#47]
The Task video for Part 1 set 2 has been added to our youtube playlist but has not been embedded yet in the gitbook resource.
#### Task description and expected result
- On the [Part 1 set 2 page ](https://obiagba-mary.gitbook.io/git-and-github-training/part-1-github-ui/set-2-learning-videos-and-tasks), under the **Tasks** section replace the text with an embedded youtube video.
- This is the youtube video to embed: https://youtu.be/IhpzEYTue34
- The video caption should be "Task for Part 1 set 2"

**Comment by Eddayavuz** [comment]
I'm happy to take this on!

**Comment by Ifycode** [comment]
Hi @Eddayavuz 
Yes, go ahead. Assigned to you!
The guideline written here should guide you on how to make and submit your changes: https://obiagba-mary.gitbook.io/git-and-github-training/contributors-guide/making-and-submitting-changes.
Let me know if you have any questions or run into any issues.

**Comment by Eddayavuz** [comment]
Hi @Ifycode I believe I did this but I couldn't test it because I didn't know how to run it on gitbook. I guess I need to be on your team? Please let me know if there's any problem and I'll try again.

**Comment by Ifycode** [comment]
Left you comments on your pull request @Eddayavuz 👍🏽
