### ISSUE TITLE
Convert Part 1 texts to links in training repo readme

### ISSUE THREAD

**Issue by Ifycode** [Ifycode/git-github-training-resource#5]
#### Task description
- Go to the readme file of the [training repo](https://github.com/Ifycode/git-github-training)
- Convert the list item text "Set 1 - Github UI Learning videos and tasks" to a link that leads to: https://obiagba-mary.gitbook.io/git-and-github-training/part-1-github-ui/set-1-github-ui-learning-videos-and-tasks
- Convert the list item text "Set 2 - Github UI Learning videos and tasks" to a link that leads to: https://obiagba-mary.gitbook.io/git-and-github-training/part-1-github-ui/set-2-github-ui-learning-videos-and-tasks

**Comment by yrs147** [comment]
I'd like to do it

**Comment by Ifycode** [comment]
Go ahead @yrs147 Thank you!

**Comment by Ifycode** [comment]
Go ahead @yrs147 Thank you!

Please note: Don't make changes direct in the main or develop branch.
Create a branch from develop branch and send a pull request to develop branch.

**Comment by yrs147** [comment]
Thank You

**Comment by Ifycode** [comment]
Hi @yrs147 Here is a comprehensive note on how to make your changes in the training repo:
 - Fork the [training repo](https://github.com/Ifycode/git-github-training) (Additional information: The default branch of the [training repo](https://github.com/Ifycode/git-github-training) is the main branch. So on the "Create a new fork" page, make sure to uncheck the "Copy the main branch only" checkbox before clicking on the "create fork" button. This will allow you to also have the develop branch, since you will need the develop branch for the next steps).
  - Go to the develop branch of your fork. 
  - Create a new branch from the develop branch and make your changes in the new branch you created.
  - Send a pull request pointing to the develop branch of the original training repo.
  - Wait for review of your changes from the repo admin(s).

**Comment by Ifycode** [comment]
Assigning this to someone else. Who wants to take up this issue?

**Comment by oyenuga17** [comment]
I am interested @Ifycode

**Comment by Ifycode** [comment]
Assigned to you @oyenuga17
