### ISSUE TITLE
Video captions on Part 1 set 1 page do not show what videos are about

### ISSUE THREAD

**Issue by Ifycode** [Ifycode/git-github-training-resource#55]
#### Problem
- Videos under the **learning videos** section of [Part 1 set 1 page](https://obiagba-mary.gitbook.io/git-and-github-training/part-1-github-ui/set-1-github-ui-learning-videos-and-tasks) have "Youtube Video" as youtube caption, this does not show what the videos are about.

#### Tasks description and expected output
Not really sure what the video captions should say. Should the video captions be the same as the header above each of them? This looks like repetition.
- What is your opinion? (drop your opinion in the comment below)
- Be willing to send a pull request to fix this issue once your opinion is accepted

**Comment by Dkingofcode** [comment]
@Ifycode  I would like to take up this issue.

**Comment by Ifycode** [comment]
Yes, assigned to you @Dkingofcode 
The guideline written here should guide you on how to make and submit your changes: https://obiagba-mary.gitbook.io/git-and-github-training/contributors-guide/making-and-submitting-changes. 
Let me know if you have any questions or run into any issue.

**Comment by Ifycode** [comment]
Click on the link in the issue description to find videos.

**Comment by Dkingofcode** [comment]
@Ifycode, I think the caption should contain the necessary information about the youtube video and the header should just contain either serial numbers or serial  numbers with short descriptions. e.g. 1. forking.

**Comment by Dkingofcode** [comment]
@Ifycode  If you have additional videos on the same topic, the headings could provide organisation for them.

**Comment by Ifycode** [comment]
The part about the caption makes sense. Let's just remove the video titles totally. Then what was previously title should be the video caption.
