### ISSUE TITLE
Help contributors know how to submit contributions to the Git and github training Documentation repo

### ISSUE THREAD

**Issue by Ifycode** [Ifycode/git-github-training-resource#6]
#### Problem
We currently do not have our workflow written out for the documentation repo. So right now, contributors don't have much help on how they can interact with the training and documentation repos when they make contributions. We want to change that.

#### Task description and expected result

- On the [Making and submitting changes](https://obiagba-mary.gitbook.io/git-and-github-training/contributors-guide/making-and-submitting-changes) page of the documentation, there is a section in there with title **Add your changes using the GitHub UI**, change this title to **Documentation repo: Add your changes using the GitHub UI**
- Replace "Add text content" with the following information in form of a list:
  - Fork the [documentation repo](https://github.com/Ifycode/git-github-training-documentation) (Additional information: The default branch of the [documentation repo](https://github.com/Ifycode/git-github-training-documentation) has been set to develop branch. So on the "Create a new fork" page, you can leave the "Copy the develop branch only" checkbox as checked since you will need the develop branch for the next steps).
  - Confirm that you are in the develop branch of your fork.
  - Create a new branch from the develop branch and make your changes in the new branch you created.
  - Send a pull request pointing to the develop branch of the original documentation repo.
  - Wait for review of your changes from the repo admin(s). 

Feel free to add any other helpful information to the list that I may have missed out on, but your submission must contain everything in the list above.

> **Note**
> Find file to update in the doc folder of this repository

**Comment by oyenuga17** [comment]
I am interested in this issue  @Ifycode

**Comment by Ifycode** [comment]
Assigned to you @oyenuga17
