### ISSUE TITLE
Add hint to show contributors direction on the contributing guidelines page

### ISSUE THREAD

**Issue by Ifycode** [Ifycode/git-github-training-resource#66]
#### Task description and expected output
There are 2 links on the [contributing guidelines](https://obiagba-mary.gitbook.io/git-and-github-training/contributors-guide/contributing-guidelines) page - i.e. links to the code of conduct .md file and how to submit your changes to this training resource page.
- Add a hint just before the links.
- The content of the hint: You can start with "Hi there 👋 Thank you for your interest to contribute to the [Git and Github training resource](https://obiagba-mary.gitbook.io/git-and-github-training/contributors-guide/contributing-guidelines)". Tell the reader to find the guidelines for contributing to the training resource in the links below.

> **Note**
> Interested contributors should read up [How to submit your changes to this training resource](https://obiagba-mary.gitbook.io/git-and-github-training/contributors-guide/making-and-submitting-changes) for guidelines on how to make contributions to this repository

**Comment by Ifycode** [comment]
Go ahead @LucianeFernandesRoque 👍🏽
Do let me know if you have any issues or need help at any point.

**Comment by LucianeFernandesRoque** [comment]
> Go ahead @LucianeFernandesRoque 👍🏽 Do let me know if you have any issues or need help at any point.

Sorry, Sometimes i have difficult with English language, But I think so understand you in relation my PR.
I made the changes that were requested. Thank u soo much for your attention.

**Comment by Ifycode** [comment]
OK @LucianeFernandesRoque thank you for letting me know. I will also try to keep my English simple for you sake.
Check the pull request to see my new comment.

**Comment by Ifycode** [comment]
👍💯
