### ISSUE TITLE
Help contributors easily find the contributors guide

### ISSUE THREAD

**Issue by Ifycode** [Ifycode/git-github-training-resource#69]
#### Issue Background
In open source, the contributing guide for a project is usually expected to be in the CONTRIBUTING.md file at the root of the project repository.
The git and Github training resource has a [contributing guide](https://obiagba-mary.gitbook.io/git-and-github-training/contributors-guide/contributing-guidelines), but we do not have it at the root of the project and inside a CONTRIBUTING.md file. The reason is that we want the contributing guidelines to show up in our Gitbook resource.

#### Task description and expected output
Just in case an interested contributor prefers to look for a CONTRIBUTING.md file since it's like an open-source norm, you will help redirect them to the gitbook contributing guidelines. The task is simple:
- Create a CONTRIBUTING.md file at the root of the repo.
- In this file, let the reader know that the contributing guidelines can be found on the [contributing guidelines page](https://obiagba-mary.gitbook.io/git-and-github-training/contributors-guide/contributing-guidelines) of the git and Github training gitbook learning resource.

**Comment by g33tansh** [comment]
Hey! I would like to work on this issue.

**Comment by Ifycode** [comment]
Yes please go ahead @g33tansh 👍

**Comment by Ifycode** [comment]
Read up [How to submit your changes to this training resource](https://obiagba-mary.gitbook.io/git-and-github-training/contributors-guide/making-and-submitting-changes) for guidelines on how to make contributions to this repository.
