### ISSUE TITLE
Help contributors know how to submit contributions to the Git and github training repo

### ISSUE THREAD

**Issue by Ifycode** [Ifycode/git-github-training-resource#7]
#### Problem
We currently do not have our workflow written out for the training repo. So right now, contributors don't have much help on how they can interact with the training and documentation repos when they make contributions. We want to change that.

#### Task description and expected result

On the [Making and submitting changes](https://obiagba-mary.gitbook.io/git-and-github-training/contributors-guide/making-and-submitting-changes) page of the documentation:
- Add a new section just before the "Add your changes using the command line" section. The name of the new section should be **Training repo: Add your changes using the GitHub UI** 
- Under this new section you created, add the following information in form of a list:
  - Fork the [training repo](https://github.com/Ifycode/git-github-training) (Additional information: The default branch of the [training repo](https://github.com/Ifycode/git-github-training) is the main branch. So on the "Create a new fork" page, make sure to uncheck the "Copy the main branch only" checkbox before clicking on the "create fork" button. This will allow you to also have the develop branch, since you will need the develop branch for the next steps).
  - Go to the develop branch of your fork. 
  - Create a new branch from the develop branch and make your changes in the new branch you created.
  - Send a pull request pointing to the develop branch of the original training repo.
  - Wait for review of your changes from the repo admin(s). 

Feel free to add any other helpful information to the list that I may have missed out on, but your submission must contain everything in the list above.

> **Note**
> Find file to update in the doc folder of this repository

**Comment by Dkingofcode** [comment]
I'm interested in this isuue ma. @Ifycode

**Comment by Ifycode** [comment]
Assigned to you @Dkingofcode
